// <auto-generated />
using System;
using System.Collections.Generic;
using FeedService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FeedService.Migrations
{
    [DbContext(typeof(FeedDbContext))]
    [Migration("20261005085350_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FeedService.Models.PostSnapshot", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AuthorHeadline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthorProfileImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Content")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("Hashtags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPureRepost")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("MentionedUserIds")
                        .IsRequired()
                        .HasColumnType("bigint[]");

                    b.Property<string>("RepostOfAuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RepostOfAuthorId")
                        .HasColumnType("text");

                    b.Property<string>("RepostOfContent")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<long?>("RepostOfPostId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_PostSnapshots_AuthorId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PostSnapshots_CreatedAt");

                    b.HasIndex("AuthorId", "CreatedAt")
                        .HasDatabaseName("IX_PostSnapshots_Author_CreatedAt")
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("PostSnapshots", (string)null);
                });

            modelBuilder.Entity("FeedService.Models.UserSummary", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Headline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfileImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_UserSummaries_UpdatedAt");

                    b.ToTable("UserSummaries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
